[package]
name    = "fast_dom"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ecow       = "0.2.0"
rustc-hash = "1.1.0"
re_css     = { path = "../re_css" }
