[package]
name    = "fast_html"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tree       = { path = "../../utilities/tree" }
fast_dom   = { path = "../fast_dom" }
ecow       = "0.2.0"
log        = "0.4.20"
serde_json = "1.0.111"
once_cell  = "1.19.0"
rustc-hash = "1.1.0"

[dev-dependencies]
assert-json-diff = "2.0.2"
criterion        = { version = "0.5.1", features = ["html_reports"] }

[[bench]]
name    = "parse_html"
path    = "benches/parse_html.rs"
harness = false

[[bench]]
name    = "tokenizer"
path    = "benches/tokenizer.rs"
harness = false

[[bench]]
name    = "with_attributes"
path    = "benches/with_attributes.rs"
harness = false

[[bench]]
name    = "named_char_ref"
path    = "benches/named_char_ref.rs"
harness = false
